const moment = require('moment')
const fechaDeNacimiento = moment([1998, 6, 14])
const presente = moment()
const añosDesde = presente.diff(fechaDeNacimiento, 'years')
const diasDesde = presente.diff(fechaDeNacimiento, 'days')
//console.log(moment().format('DD/MM/YYYY'))
console.log(`Hoy es ${moment().format('DD/MM/YYYY')}`)
console.log(`Nací el ${fechaDeNacimiento.format('DD/MM/YYYY')}`)
console.log(`Desde mi nacimiento han pasado ${añosDesde} años`)
console.log(`Desde mi nacimiento han pasado ${diasDesde} días`)